### ISSUE TITLE
Text Editor Height Increases continuously by clicking or typing on it

### ISSUE THREAD

**Issue by peeyushsrj** [featherplain/amethyst#140]
I recently updated from 1.0.4 to 1.1.0, after that when I was editing my posts. I find unusual behavior of change in height while typing or by clicking on the editor. 
I verified this by switching to another theme where it was all normal. I again installed Amethyst 1.1.0, still getting the same bug.

**Comment by peeyushsrj** [comment]
I tried from different browsers: UC and Opera Browser. Same bug!

**Comment by peeyushsrj** [comment]
Roll back to "editor-style.css" of version 1.0.4. And bug will be gone.

**Comment by peeyushsrj** [comment]
Suggestion: This is serious problem! Please update in your repo and wordpress website. Otherwise users might switch to other themes.

**Comment by featherplain** [comment]
fixed at release v2.0.0
